name: FX Tracker

on:
  schedule:
    - cron: "0 22 * * *"   # Runs daily (UTC)
  workflow_dispatch:      # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python fx_tracker.py

      - name: Commit market_data.csv
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
            
          git add market_data.csv
            
          git commit -m "Update market data CSV" || echo "No changes to commit"
            
          git push

